### ISSUE TITLE
Intermittent possible testing failure on: Linux + Perl 5.10.0 + threaded

### ISSUE THREAD

**Issue by plicease** [Perl5-FFI/FFI-Platypus#68]
Reported via cpantesters here:

http://www.cpantesters.org/cpan/report/31510684-43e0-11e6-ab41-c893a58a4b8c

I tried to reproduce this on Debian + Perl 5.10.0 + threaded + libffi 3.2.1, which matches the report as closely as I could manage, but the t/threads.t test passes for me.

The test that is failing is thread specific and is only run on threaded Perls.  All other tests seem fine.

@bingos if you have any ideas about the environment of the testing machine might have triggered this I'd be interested.

**Comment by plicease** [comment]
I am now able to reproduce using 32bit debian:

```
twin-i386% perl -Mblib t/threads.t 
1..2
# 
# 
# 
# Note that there are known but unresolved issues with Platypus on threaded 5.10.0 Perls.
# If you know that you will not be using threads you can safely ignore any failures with
# this test.  If you need threads you can either upgrade to 5.10.1+ or downgrade to 5.8.9-
# 
# You can also follow along with this issue here:
# https://github.com/plicease/FFI-Platypus/issues/68
# 
# 
Segmentation fault
```

I started suspecting 32bit because the ABIs listed didn't match what I expected for 64 bit even though the machine code was `x86_64-linux-thread-multi`.  I notice that the 32bit Perl that I build in a chroot also uses this code, probably because it uses the output of `uname`.

**Comment by plicease** [comment]
stack trace (not particularly useful):

(gdb) bt
#0  0x080b1e5f in Perl_parser_dup ()
#1  0x080bb0f5 in perl_clone ()
#2  0xf7bb580b in XS_threads_create () from /home/ollisg/perl5/deb32/perls/perl-5.10.0t/lib/5.10.0/x86_64-linux-thread-multi/auto/threads/threads.so
#3  0x080aed05 in Perl_pp_entersub ()
#4  0x080a72e1 in Perl_runops_standard ()
#5  0x080a3d2c in perl_run ()
#6  0x08060964 in main ()

**Comment by plicease** [comment]
Also happens with a real 32 bit Perl with the real archname:

```
debian32% pconfig archname
archname=i686-linux-thread-multi
debian32% perl -Mblib t/threads.t 
1..2
# 
# 
# 
# Note that there are known but unresolved issues with Platypus on threaded 5.10.0 Perls.
# If you know that you will not be using threads you can safely ignore any failures with
# this test.  If you need threads you can either upgrade to 5.10.1+ or downgrade to 5.8.9-
# 
# You can also follow along with this issue here:
# https://github.com/plicease/FFI-Platypus/issues/68
# 
# 
Segmentation fault
```

**Comment by plicease** [comment]
added a comment 8caf598, but at this point it seems unlikely that this will ever be fixed.

**Comment by plicease** [comment]
I get this on 64bit 5.10.0 threaded as well now.
